# spring:
#   datasource:
#      url: jdbc:sqlserver://demoservermain.database.windows.net:1433;database=demoDb;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
#      username: mainak
#      password: HelloWorld123@
#   jpa:
#      show-sql: true
#      hibernate:
#      ddl-auto: create
#      dialect: org.hibernate.dialect.SQLServer2012Dialect

# server:
#   port: 9090

  